from .clean_data import clean_variable
from .format_data import format_variable
from .conversions import kelvin_to_celsius, meters_per_second_to_mph, meters_per_second_to_knots_per_hour, knots_per_hour_to_mph, mph_to_knots_per_hour